name: C/C++ CI

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    container: 
      image: 'emscripten/emsdk:latest'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install packages
        run: |
          sudo apt update
          sudo apt install wabt

      - name: Test
        working-directory: tests/basic
        run: |
          chmod +x run.sh
          CC=emcc CFLAGS="" ./run.sh
